allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@next/env@16.2.7 || 16.2.9'
  - '@next/swc-darwin-arm64@16.2.7 || 16.2.9'
  - '@next/swc-darwin-x64@16.2.7 || 16.2.9'
  - '@next/swc-linux-arm64-gnu@16.2.7 || 16.2.9'
  - '@next/swc-linux-arm64-musl@16.2.7 || 16.2.9'
  - '@next/swc-linux-x64-gnu@16.2.7 || 16.2.9'
  - '@next/swc-linux-x64-musl@16.2.7 || 16.2.9'
  - '@next/swc-win32-arm64-msvc@16.2.7 || 16.2.9'
  - '@next/swc-win32-x64-msvc@16.2.7 || 16.2.9'
  - next@16.2.7 || 16.2.9
  - react-dom@19.2.7
  - react@19.2.7
  - miniflare@5.20260910.0-alpha
  - wrangler@4.131.0


overrides:
  miniflare>undici: 7.30.0
